name: LuminaryBackpacks
version: '1.0.0'
main: com.luminary.backpacks.LuminaryBackpacks
api-version: '1.20'
author: Luminary
description: Virtual backpacks with auto-pickup and auto-sell for prison mining
depend: [LuminaryCore]
softdepend:
  - LuminaryEconomy
  - PlaceholderAPI

commands:
  backpack:
    description: Open your backpack
    usage: /<command> [tier]
    aliases: [bp]
  backpackadmin:
    description: Admin backpack commands
    usage: /<command> <subcommand>
    aliases: [bpadmin]

permissions:
  luminarybackpacks.use:
    description: Use backpacks
    default: true
  luminarybackpacks.autosell:
    description: Use auto-sell feature
    default: true
  luminarybackpacks.autopickup:
    description: Use auto-pickup feature
    default: true
  luminarybackpacks.admin:
    description: Admin commands
    default: op
